=== BackupTheBerlios/qa-assistant-svn/fedora-rpmdevtools/trunk/data/checklist.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT checklist (category+)>
  <!ATTLIST checklist
    version CDATA #FIXED '0.1'
    name CDATA #REQUIRED
    revision CDATA #REQUIRED
  >
  <!ELEMENT category (description, entry+)>
    <!ATTLIST category
      name CDATA #REQUIRED
    >
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT entry (display, states, description, input?)>
      <!ATTLIST entry
        name CDATA #REQUIRED
      >
      <!ELEMENT display EMPTY>
        <!ATTLIST display
          default (true|false) #REQUIRED
        >
      <!ELEMENT states (state+)>
        <!ELEMENT state (output?)>
          <!ATTLIST state
            name (Needs-Reviewing|Pass|Fail|Non-Blocker|Not-Applicable) #REQUIRED
          >
          <!ELEMENT output (#PCDATA)>
        <!ELEMENT input (#PCDATA)>

=== BackupTheBerlios/qa-assistant-svn/trunk/data/minimal-valid.xml
<?xml version='1.0' ?>
<!DOCTYPE checklist PUBLIC "-//BadgerWare//DTD QA Assistant Checklist File 0.3//EN" "http://qa-assistant.sf.net/dtds/checklist/0.3/checklist.dtd">
<checklist version="0.3" name="Little Do Nothing" revision="0.1">
  <summary>Test for crashing with no values</summary>
  <category name="Minimal one item category">
    <description>
    </description>
    <entry name="Minimal single entry">
      <states>
        <state name="Pass"></state>
      </states>
      <description>
      </description>
    </entry>
  </category>
</checklist>
