=== BackupTheBerlios/qa-assistant-svn/qa-assistant/trunk/data/qasave.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ENTITY % Resolutions '(Needs-Reviewing|Pass|Fail|Non-Blocker|Not-Applicable)'>
<!ELEMENT qasave (checklist, properties?, entry+)>
  <!ATTLIST qasave
    version CDATA #FIXED '0.1'
  >
  <!ELEMENT checklist (#PCDATA)>
    <!ATTLIST checklist
      name CDATA #REQUIRED
      revision CDATA #REQUIRED
    >
  <!ELEMENT properties (property+)>
    <!ELEMENT property (#PCDATA)>
      <!ATTLIST property
        name CDATA #REQUIRED
      >
  <!ELEMENT entry (states?)>
    <!ATTLIST entry
      name CDATA #REQUIRED
      display (true|false) "false"
      state %Resolutions; #REQUIRED
    >
      <!ELEMENT states (state+)>
        <!ELEMENT state (#PCDATA)>
          <!ATTLIST state
            name %Resolutions; #REQUIRED
          >

=== BackupTheBerlios/qa-assistant-svn/qa-assistant/trunk/data/sample-save.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE qasave SYSTEM 'qasave.dtd'>
<qasave version='0.1'>
  <checklist name='fedoraus' revision='0.1'/>
  <properties>
    <property name='BugzillaId'>11452</property>
    <property name='BugzillaURL'>http://bugzilla.somebugzillaurl.com/cgi-bin/bugquery</property>
  </properties>
  <entry name='Epoch' display='true' state='Fail'>
    <states>
      <state name='Fail'>Epoch is incorrect</state>
      <state name='Pass'>Epoch is correct</state>
    </states>
  </entry>
  <entry name='SRPM Signature' display='true' state='Pass'>
    <states>
      <state name='Fail'>This is a failur</state>
    </states>
  </entry>
</qasave>
