=== BackupTheBerlios/qa-assistant-svn/tags/0.4.90.5/data/checklist.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
 Identifiers:
 PUBLIC "-//BadgerWare//DTD QA Assistant Checklist File 0.3//EN"
 SYSTEM "http://qa-assistant.sf.net/checklist/0.3/checklist.dtd"
-->

<!-- Valid resolutions for a checklist item. -->
<!ENTITY % Resolutions
  '(Needs-Reviewing|Pass|Fail|Non-Blocker|Not-Applicable)'
>

<!-- True or False -->
<!ENTITY % Boolean
  '(true|false)'
>

<!-- Currently recognized languages to write tests in -->
<!ENTITY % ExtensionLangs
  '(python|sh)'
>

<!-- Types available for properties.  All properties need to be of one of
     these types.
  -->
<!ENTITY % PropType
  '(string|file|url|number|md5sum|sha1sum)'
>

<!-- Requirement types for properties.  All properties need to be set to one
     of these.  The requirement types allow us to know if the property is
     needed and if so, when.

     :onload: We need to load this property at the start of the Review.
              Use this for items that are necessary for other tests to be
	      performed.
              This type must be entered by the user.
     :onpublish: The property needs to be defined before we can publish a
                 review.  This type may be entered by the user or by the
                 system over the course of the review.
     :automatic: This property is loaded through an automated test.  This
                 type cannot be entered by the user.  It is optional.
                 It will be loaded when the user loads the properties that it
		 depends on.
     :optional: The property does not need to be entered.
  -->
<!ENTITY % RequireType
  '(onload|onpublish|automatic|optional)'
>

<!-- Types of cryptographic hashes to use when summing checklist functions.
  :sha1: A sha1 type hash
  :md5: A traditional md5 hash
  :nullhash: The hash will not be checked.  Useful when developing a new
             checklist but should not be used when distributing files.
  -->
<!ENTITY % HashType
  '(sha1|md5|nullhash)'
>

<!-- Top level element

     Attributes:
     version: Version of the checklist DTD
     name: Name of this checklist
     revision: Revision of this checklist
  -->
<!ELEMENT checklist (summary, base?, functions?, properties?, category+)>
  <!ATTLIST checklist
    version CDATA #FIXED '0.3'
    name CDATA #REQUIRED
    revision CDATA #REQUIRED
  >
  
  <!-- A brief description of the checklist
  
       This is mostly used when showing users of a checklist what the
       checklist is for.
    -->
  <!ELEMENT summary (#PCDATA)>
  
  <!-- Information on the base checklist used to create this one
  
       Attributes:
       name: Name of the base checklist
       revision: Revision of the base checklist

       Content: Filename of the base checklist (Generally does not include
                  full path info at this time.)
    -->
  <!ELEMENT base (#PCDATA)>
    <!ATTLIST base
      name CDATA #REQUIRED
      revision CDATA #REQUIRED
    >
  
  <!-- File containing functions requested by the checklist.
       Attributes:
       :hash: A cryptographic hash of the file.
       :hashtype: The type of hash this is.
       Content: The name of the file in which the functions reside.
    -->
  <!ELEMENT functions (#PCDATA)>
    <!ATTLIST functions
      hash CDATA #REQUIRED
      hashtype %HashType; 'sha1'
    >

  <!-- Properties associated with the checklist such as filename,
       Issue tracking number, etc. -->
  <!ELEMENT properties (property+)>

    <!-- An individual property set on the checklist.

         Attributes:
         name: The name of the property
         type: The type of the property

         Content: The property's value.  The application should validate
                  the property's value against its type.
      -->
    <!ELEMENT property (require, function*, value?)>
      <!ATTLIST property
        name CDATA #REQUIRED
        type %PropType; #REQUIRED
      >

      <!-- Requirements for the property.

           Attributes:
           :type: When and whether the property is required.

           Content: A function to call to get the property.
        -->
      <!ELEMENT require EMPTY>
        <!ATTLIST require
          type %RequireType; #REQUIRED
        >

    <!-- Function to run to set other properties when this one is changed.
    
         Contents: The name of the function.
      -->
    <!ELEMENT function (#PCDATA)>

    <!ELEMENT value (#PCDATA)>
        
  <!-- Metainfo for a group of entries.
    
        Attributes:
        name: Name for the category.
    -->
  <!ELEMENT category (description, entry+)>
    <!ATTLIST category
      name CDATA #REQUIRED
    >
    
    <!-- Long description of the entry or category.  For categories, this
         holds an overview of the category.  For entries, it has instructions
         for evaluating an entry and filling it out.

         Content: The description text.
      -->
    <!ELEMENT description (#PCDATA)>

    <!-- A checklist item to fill out.
    
         Attributes:
         name: The name of the entry.  Should be a *brief* description and
                 unique.
         display: Whether to display the entry or not.
         state: state to set the entry to initially.
      -->
    <!ELEMENT entry (states, test?, description)>
      <!ATTLIST entry
        name CDATA #REQUIRED
        display %Boolean; "false"
        state %Resolutions; "Needs-Reviewing"
      >
      
      <!-- An automated test that may be run to fill in the value for this
           checklist item.  This should be the name of a python function to
           call to run this test.
           
       The test should take properties as arguments and return the results
       of the test as a tuple:
             First element of the tuple is a string corresponding to the
             resolution of the item (ie: Pass, Fail, etc: Anything from
             %Resolutions;)

             The second item is a string to set the output to.  This can be
         None and the program will use the string that is already set.
       
       *** WARNING: Do not depend on this.  This functionality has not yet
           been implemented and may change drastically as a result of that
           work.
        -->
      <!ELEMENT test (#PCDATA)>
         
      <!-- Allowable states for this checklist item. -->
      <!ELEMENT states (state+)>
        <!-- A state tht the checklist item may be in.
        
             Attributes:
             name: Name of the state.  Must be one of the valid resolutions.
             
             Content: The output string to print when the entry is in this
                        state.
          -->
        <!ELEMENT state (#PCDATA)>
          <!ATTLIST state
            name %Resolutions; #REQUIRED
          >

=== BackupTheBerlios/qa-assistant-svn/qa-assistant/trunk/data/minimal-valid.xml
<?xml version='1.0' ?>
<!DOCTYPE checklist PUBLIC "-//BadgerWare//DTD QA Assistant Checklist File 0.3//EN" "http://qa-assistant.sf.net/dtds/checklist/0.3/checklist.dtd">
<checklist version="0.3" name="Little Do Nothing" revision="0.1">
  <summary>Test for crashing with no values</summary>
  <functions>
    <function type="user">add_item</function>
    <function type="user">separator</function>
    <function type="user">publish</function>
  </functions>
  <category name="Minimal one item category">
    <description>
    </description>
    <entry name="Minimal single entry">
      <states>
        <state name="Pass"></state>
      </states>
      <description>
      </description>
    </entry>
  </category>
</checklist>

=== BackupTheBerlios/qa-assistant-svn/tags/0.4.90.1/data/softwarerelease.xml
<?xml version='1.0' ?>
<!DOCTYPE checklist PUBLIC "-//BadgerWare//DTD QA Assistant Checklist File 0.3//EN" "http://qa-assistant.sf.net/dtds/checklist/0.3/checklist.dtd">
<checklist version="0.3" name="Software Release" revision="0.1">
  <summary>Pre-release testing to assure a decent package</summary>
  <properties>
    <property name="softwarename" type="string">
      <require type="onload"/>
    </property>
    <property name="repositoryType" type="string">
      <require type="onload"/>
    </property>
    <property name="repositoryURL" type="url">
      <require type="onload"/>
    </property>
  </properties>
  <functions>
    <function type="user">add_item</function>
    <function type="user">separator</function>
    <function type="user">publish</function>
  </functions>
  <category name="Automated steps">
    <description>Much of the release of a new software package can be
      automated.  The following entries each have code to make the job of
      releasing a GNU software project easier.</description>
    
    <entry name="Release in Source Control" display="true">
      <states>
        <state name="Pass">The release is in the source control system</state>
        <state name="Fail">The release is not yet checked in</state>
      </states>
      <description>The source control system is a repository for code history.
        As such it is important that it contains each release of the code.
        Please make sure that checking out of the current HEAD or a TAG for
        the release will get the code we are packaging for this release.
        In a subversion environment, one way to check is::
          svn update; svn status
        Then review the list of files for ones that are not uptodate.
      </description>
    </entry>
    <entry name="autoreconf/autogen.sh" display="true">
      <states>
        <state name="Pass">Able to autoreconf/autogen.sh the source tree</state>
        <state name="Fail">autoreconf/autogen.sh fails</state>
      </states>
      <description>The source code must be able to rebuild from the sources
        checked out of the repository.  This entails doing a checkout and then
        invoking autoreconf or autogen.sh in order to recreate all the build
        files necessary to create the program.</description>
    </entry>
    <entry name="configure" display="true">
      <states>
        <state name="Pass">Able to configure the source tree</state>
        <state name="Fail">configure fails</state>
      </states>
      <description>Running configure is the next step in the process.  Does
        configure correctly assess what is available on the system?  Or does
        it perform its tests incorrectly?</description>
    </entry>
    <entry name="make dist-check" display="true">
      <states>
        <state name="Pass">make dist-check successfully creates a new distribution</state>
        <state name="Fail">make dist-check fails</state>
      </states>
      <description>Running make dist-check should create a new distribution
        tarfile.  It performs checks of the documentation, the build, and runs
        the package's regression tests to try to verify the package is
        correct.</description>
    </entry>
    <entry name="rpm creation" display="true">
      <states>
        <state name="Pass">rpms successfully build</state>
        <state name="Fail">RPMS do not build</state>
      </states>
      <description>Creating an rpm for the distribution via rpmbuild -ta
        &lt;source tarball&gt; is helpful for distributing the program.</description>
    </entry>
    <entry name="make dist-check" display="true">
      <states>
        <state name="Pass">make dist-check successfully creates a new distribution</state>
        <state name="Fail">make dist-check fails</state>
      </states>
      <description>Running make dist-check should create a new distribution
        tarfile.  It performs some checks of the documentation and build to
        make sure that is correct.</description>
    </entry>
  </category>
  <category name="Manual steps">
    <description>Some tests just have to be done manually.</description>
    <entry name="All files included" display="true">
      <states>
        <state name="Pass">All files in the source tree are in the distribution</state>
        <state name="Fail">Some files are missing</state>
      </states>
      <description>The source tarball created in make dist-check is only as
        good as the Makefile.am's that produced it.  Comparing the files in
        the tarball compared to the files in the source tree is a good way to
        tell when the Makefile.am may be missing files.</description>
    </entry>
    <entry name="runs fine" display="true">
      <states>
        <state name="Pass"></state>
        <state name="Fail"></state>
      </states>
      <description>
      </description>
    </entry>
  </category>
</checklist>
